<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Event Practice</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="../public/css/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<div class="container-fluid">
  <div id="content">
      <?php echo $this->getContent(); ?>
  </div>
</div>
</body>
</html>